# Generated by Django 5.2 on 2025-05-06 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_department_program_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gpa',
        ),
    ]
