# Generated by Django 5.2 on 2025-05-09 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_applied', models.CharField(choices=[('president', 'President'), ('deputy_president', 'Deputy President'), ('sec_gen', 'Secretary General'), ('finance', 'Finance and Labour Secretary'), ('academics_foreign', 'Academics & Foreign Affairs Secretary'), ('sports', 'Sports & Entertainment Secretary'), ('gender', 'Gender & Special Interest Secretary'), ('nursing_rep', 'Senator - School of Nursing & Health Sciences'), ('business_rep', 'Senator - Scholar of Business'), ('education_rep', 'Senator - School of Education, Humanities and Social Sciences'), ('science_rep', 'School of Science and Technology'), ('religious_rep', 'Religious Affairs Rep'), ('international_rep', 'International Rep')], max_length=50)),
                ('manifesto', models.TextField(blank=True)),
                ('application_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('eligible', models.BooleanField(default=False)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DelegateApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('on_work_study', models.BooleanField(help_text='Are you currently in the Work-Study program?')),
                ('application_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('eligible', models.BooleanField(default=False)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
