# Generated by Django 5.2 on 2025-05-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=100)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('year_of_study', models.IntegerField()),
                ('tribe', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
    ]
